name: Splunk Add-on Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout to repository
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Unit Testing
        run: |
          pipenv run pytest -v
      - name: Run Flake8
        run: |
          pipenv run flake8 ./add-on/TA-Demisto
      - name: Compress Add-on
        run: |
          mkdir $GITHUB_WORKSPACE/artifacts

          export SPL_PATH="$GITHUB_WORKSPACE/artifacts/demisto-add-on-for-splunk.tgz"
          echo "SPL_PATH=$SPL_PATH" >> $GITHUB_ENV

          cd add-on
          COPYFILE_DISABLE=1 tar -cvzf $SPL_PATH --exclude='*.pyc' TA-Demisto
      - name: Upload tar file to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: demisto-add-on-for-splunk.tgz
          path: ${{ env.SPL_PATH }}
      - name: Run AppInspect
        env:
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
          SPL_PATH: ${{ env.SPL_PATH }}
        run: |
          pipenv run python .github/appinspect.py $SPLUNK_USERNAME $SPLUNK_PASSWORD $SPL_PATH
