name: Splunk Add-on Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout to repository
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python3 -m pip install flake8
          python3 -m pip install requests
          python3 -m pip install pytest-splunk-addon
      - name: Run Flake8
        run: |
          flake8 ./add-on/TA-Demisto
      - name: Compress Add-on
        env:
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
        run: |
          mkdir $GITHUB_WORKSPACE/artifacts

          export SPL_PATH="$GITHUB_WORKSPACE/artifacts/demisto-add-on-for-splunk.tgz"
          echo ::set-env name=SPL_PATH::$SPL_PATH

          tar -cvzf $SPL_PATH ./add-on/TA-Demisto
      - name: Upload tar file to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: demisto-add-on-for-splunk.tgz
          path: ${{ env.SPL_PATH }}
      - name: Run AppInspect
        env:
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
          SPL_PATH: ${{ env.SPL_PATH }}
        run: |
          python3 .github/appinspect.py $SPLUNK_USERNAME $SPLUNK_PASSWORD $SPL_PATH
      - name: Setup Splunk Environment
      - env:
          SPLUNK_HOST: https://localhost
          SPLUNK_PORT: 8000
          SPL_PATH: ${{ env.SPL_PATH }}
      - run: |
          docker run -d -p "8000:8000" -p "8088:8088" -p "8089:8089" -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=changeme" --name splunk splunk/splunk:latest
          IS_CONTAINER_HEALTHY=1
          while [ "$IS_CONTAINER_HEALTHY" = 1 ]
          do
             sleep 5
             CONTAINER_STATUS=$(docker inspect --format='{{.State.Health.Status}}' splunk)
             [ "$CONTAINER_STATUS" = "healthy" ] ; IS_CONTAINER_HEALTHY=$?
          done
          echo "Container is ready!"
          pytest --splunk-type=external --splunk-app=$SPL_PATH --splunk-host=$SPLUNK_HOST --splunk-port=$SPLUNK_PORT --splunk-user=admin --splunk-password=changeme

