name: Splunk Add-on Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout to repository
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python3 -m pip install flake8
          python3 -m pip install requests
      - name: Run Flake8
        run: |
          flake8 ./add-on/TA-Demisto
      - name: Compress Add-on
        env:
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
        run: |
          mkdir $GITHUB_WORKSPACE/artifacts
          export SPL_PATH="$GITHUB_WORKSPACE/artifacts/demisto-add-on-for-splunk.tgz"
          echo "::set-env name=SPL_PATH::$SPL_PATH"
          echo "SPL_PATH=$SPL_PATH"
          tar -cvzf $SPL_PATH --one-file-system ./add-on/TA-Demisto
          python3 .github/appinspect.py $SPLUNK_USERNAME $SPLUNK_PASSWORD $SPL_PATH
      - name: Upload tar file to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar-file
          path: ${{ env.SPL_PATH }}
      - name: Run AppInspect
        env:
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
        run: |
          python3 .github/appinspect.py $SPLUNK_USERNAME $SPLUNK_PASSWORD $SPL_PATH

